/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.swing;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.UnknownHostException;

import javax.swing.JFrame;

import network.FetchMyIPv4Address;
import network.ListenOnAPort;
import util.Property;
import util.ThreadUtil;

/**
 *
 * @author PRINCIPAL
 */
public class GameSettingsPanel extends javax.swing.JPanel {

    private JFrame rummyOLan;
    
    /**
     * Creates new form HostGameOnClickPanel
     */
    public GameSettingsPanel() {//TODO make private?
        initComponents();
    }

    public GameSettingsPanel(JFrame rummyOLan) {
        this();
        this.rummyOLan = rummyOLan;
        setGameSettingsLabelText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameSettingsLabel = new javax.swing.JLabel();
        hostButton = new javax.swing.JButton();

        gameSettingsLabel.setToolTipText("");

        hostButton.setText("Host");
        hostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostButton)
                    .addComponent(gameSettingsLabel))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(gameSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(hostButton)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostButtonActionPerformed
        // TODO add your handling code here:
        String hostIP = null;
        try {
            hostIP = FetchMyIPv4Address.fetchMyIPv4Address();
        } catch (UnknownHostException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        int serverListenPort = 0;
        try {
            ServerSocket serverSocket = ListenOnAPort.listenOnAPort();
            serverListenPort = serverSocket.getLocalPort();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        String hostDetails = "Host Details - " + hostIP + ":" + serverListenPort;
        Property.value.put(Property.Key.HOST_DETAILS, hostDetails);
        
        rummyOLan.setContentPane(new HostDetailsPanel());
        rummyOLan.pack();
    }//GEN-LAST:event_hostButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameSettingsLabel;
    private javax.swing.JButton hostButton;
    // End of variables declaration//GEN-END:variables

    private void setGameSettingsLabelText() {
        String text = "<HTML><u>Game&nbsp;Settings</u></HTML>";
        gameSettingsLabel.setText(text);
    }
}
