/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.swing;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.UnknownHostException;
import network.FetchMyIPv4Address;
import network.ListenOnAPort;

/**
 *
 * @author Dr. Vijaya
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hostGameButton = new javax.swing.JButton();
        hostDetailsLabel = new javax.swing.JLabel();

        hostGameButton.setText("Host Game");
        hostGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hostGameButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(hostDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(hostGameButton)
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hostDetailsLabel, hostGameButton});

    }// </editor-fold>//GEN-END:initComponents

    private void hostGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostGameButtonActionPerformed
        // TODO add your handling code here:
        String hostIP = null;
        try {
            hostIP = FetchMyIPv4Address.fetchMyIPv4Address();
        } catch (UnknownHostException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        int serverListenPort = 0;
        try {
            ServerSocket serverSocket = ListenOnAPort.listenOnAPort();
            serverListenPort = serverSocket.getLocalPort();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        hostGameButton.setEnabled(false);
        hostDetailsLabel.setText("Host Details - " + hostIP + ":" + serverListenPort);
    }//GEN-LAST:event_hostGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hostDetailsLabel;
    private javax.swing.JButton hostGameButton;
    // End of variables declaration//GEN-END:variables
}
